### PR TITLE
Stop `SeqStream` errors from crashing parent app — remove "destroy" from onError

### LINKED ISSUE #24: onError doesn't properly handle errors
This issue has crashed my server and set me back a few hours.

The function you pass into `onError` property of SeqConfig (createStream method argument) gets called on an error, but at the same time another error is being emitted by the SeqStream which is not handled.

To alleviate that, you need to setup your logger as follows:

````
const streams = []
const seqStream = bunyanSeq.createStream({
    serverUrl: 'http://X.Y.Z.W',
    level: 'info',
    apiKey: 'ABCDE',
    onError: (e: Error) => { 
        console.trace('Logging failed:', e);
   }
})

seqStream.stream.on('error', (e) => console.trace('Now this is what I call error!',e)) // This is the important line
streams.push(seqStream)

let log: any = bunyan.createLogger({
  name: 'myAwesomeLogger',
  streams: streams
})

````

If you don't do that, any error that arises from stream misconfiguration or (as happened to me) from an outage of the logging server, will crash your app.

### PR DESCRIPTION
**Pull request by larenelg**
Fixes https://github.com/datalust/bunyan-seq/issues/24

### CODE REVIEW

**Comment by larenelg** [comment]
I have a linting commit in this PR — for actual changes just view https://github.com/datalust/bunyan-seq/pull/25/commits/3d4efef425095eb76607cf0e5550bb10803f8aac

File: seq_stream.js [hunk 1]
```diff
@@ -43,7 +38,8 @@ class SeqStream extends stream.Writable {
             try {
                 this._logger.emit(seqEntry);
             } catch (err) {
-                console.error(err, seqEntry);
+                this._logger.emit(err);
+                //console.error(err, seqEntry);
```
Comment (larenelg) [inline seq_stream.js]: this was an experiment and is reverted

**Review by nblumhardt — APPROVED** [review]
